import { useState, useEffect } from 'react';
import {
  Box,
  Button,
  FormControl,
  MenuItem,
  Paper,
  Select,
  Stack,
  Tab,
  Tabs,
  Typography,
} from '@mui/material';
import {
  BoltRounded,
  ContentCopyRounded,
  FileDownloadRounded,
  RefreshRounded,
} from '@mui/icons-material';

import {
  useAASContext,
  type SubmodelTemplate,
  type SubmodelElement,
  type SubmodelElementChild,
} from '@/context/AASContext';
import { useDialogContext } from '@/context/DialogContext';

// ═══════════════════════
// GENERATION STEPS
// ═══════════════════════

const GEN_STEPS = [
  'Parsing AAS metamodel…',
  'Generating Pydantic schemas…',
  'Creating route handlers…',
  'Building OpenAPI spec…',
  'Writing Dockerfile & Compose…',
  'Validating IDTA-01002-3-0…',
  '✓ Server generated',
];

// ═══════════════════════
// CODE GENERATORS
// ═══════════════════════

function q(s: string): string {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

function serializeElement(el: SubmodelElement | SubmodelElementChild, depth = 3): string {
  const pad = '    '.repeat(depth);
  const inner = '    '.repeat(depth + 1);
  const lines: string[] = [
    inner + '"modelType": ' + q(el.type),
    inner + '"idShort": ' + q(el.idShort),
  ];
  if (el.semanticId) {
    lines.push(
      inner + '"semanticId": {"type": "ExternalReference", "keys": [{"type": "GlobalReference", "value": ' + q(el.semanticId) + '}]}',
    );
  }
  if (el.type === 'Property') {
    if (el.valueType) lines.push(inner + '"valueType": ' + q(el.valueType));
    lines.push(inner + '"value": ""');
  } else if (el.type === 'MultiLanguageProperty') {
    lines.push(inner + '"value": [{"language": "en", "text": ""}]');
  } else if (el.type === 'SubmodelElementCollection') {
    const smEl = el as SubmodelElement;
    if (smEl.children && smEl.children.length > 0) {
      const childStr = smEl.children.map(c => serializeElement(c, depth + 2)).join(',\n');
      lines.push(inner + '"value": [\n' + childStr + '\n' + inner + ']');
    } else {
      lines.push(inner + '"value": []');
    }
  } else if (el.type === 'Operation') {
    lines.push(inner + '"inputVariables": []');
    lines.push(inner + '"outputVariables": []');
    lines.push(inner + '"inoutputVariables": []');
  } else if (el.type === 'File' || el.type === 'Blob') {
    const ct = ('contentType' in el && el.contentType) ? el.contentType : 'application/octet-stream';
    lines.push(inner + '"contentType": ' + q(ct));
    lines.push(inner + '"value": ""');
  } else if (el.type === 'ReferenceElement') {
    lines.push(inner + '"value": None');
  }
  return pad + '{\n' + lines.join(',\n') + '\n' + pad + '}';
}

function generateMainPy(
  aasIdShort: string,
  assetId: string,
  version: string,
  assetKind: string,
  submodels: SubmodelTemplate[],
): string {
  const aasUrn = 'urn:generated:' + aasIdShort;

  const smRefs = submodels.map(sm => {
    const smUrn = 'urn:generated:' + aasIdShort + ':' + sm.idShort;
    return (
      '            {"type": "ExternalReference", "keys": [{"type": "Submodel", "value": ' + q(smUrn) + '}]}'
    );
  }).join(',\n');

  const smEntries = submodels.map(sm => {
    const smUrn = 'urn:generated:' + aasIdShort + ':' + sm.idShort;
    const elements = sm.elements.length
      ? sm.elements.map(e => serializeElement(e)).join(',\n')
      : '';
    return (
      '    ' + q(smUrn) + ': {\n' +
      '        "id": ' + q(smUrn) + ',\n' +
      '        "idShort": ' + q(sm.idShort) + ',\n' +
      '        "description": [{"language": "en", "text": ' + q(sm.description || sm.idShort) + '}],\n' +
      '        "semanticId": {"type": "ExternalReference", "keys": [{"type": "GlobalReference", "value": ' + q(sm.semanticId) + '}]},\n' +
      '        "submodelElements": [\n' +
      elements + '\n' +
      '        ],\n' +
      '    }'
    );
  }).join(',\n');

  return (
`# Auto-generated AAS Server — ` + aasIdShort + `
# IDTA-01002-3-0 Part 2 compliant — Generated by AASStudio

import base64
from typing import Any

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title=` + q(aasIdShort + ' AAS Server') + `,
    version=` + q(version) + `,
    description="AAS Server — Generated by AASStudio (IDTA-01002-3-0)",
    docs_url="/api/docs",
    redoc_url="/api/redoc",
    openapi_url="/api/openapi.json",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── In-memory store ──────────────────────────────────────────────

_SHELLS: dict[str, dict] = {
    ` + q(aasIdShort) + `: {
        "id": ` + q(aasUrn) + `,
        "idShort": ` + q(aasIdShort) + `,
        "assetInformation": {
            "assetKind": ` + q(assetKind) + `,
            "globalAssetId": ` + q(assetId) + `,
        },
        "submodels": [
` + smRefs + `
        ],
    }
}

_SUBMODELS: dict[str, dict] = {
` + smEntries + `
}

_CONCEPT_DESCRIPTIONS: dict[str, dict] = {}


# ── helpers ──────────────────────────────────────────────────────

def _unb64(encoded: str) -> str:
    try:
        padded = encoded + "=" * (-len(encoded) % 4)
        return base64.urlsafe_b64decode(padded).decode()
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid base64url identifier: " + encoded)


def _paged(items: list, limit: int, cursor: int) -> dict:
    end = cursor + limit
    page = items[cursor:end]
    return {"result": page, "paging_metadata": {"cursor": str(end) if end < len(items) else None}}


def _resolve_element(elements: list[dict], path: list[str]) -> dict | None:
    for el in elements:
        if el.get("idShort") == path[0]:
            if len(path) == 1:
                return el
            children = el.get("value", [])
            if isinstance(children, list):
                return _resolve_element(children, path[1:])
    return None


# ── /shells ──────────────────────────────────────────────────────

@app.get("/shells", tags=["AAS Repository"])
async def get_all_shells(
    limit: int = Query(100, ge=1, le=1000),
    cursor: int = Query(0, ge=0),
):
    return _paged(list(_SHELLS.values()), limit, cursor)


@app.post("/shells", status_code=201, tags=["AAS Repository"])
async def create_shell(shell: dict):
    sid = shell.get("idShort") or shell.get("id")
    if not sid:
        raise HTTPException(status_code=400, detail="Shell must have 'idShort' or 'id'")
    if sid in _SHELLS:
        raise HTTPException(status_code=409, detail="Shell '" + str(sid) + "' already exists")
    _SHELLS[sid] = shell
    return shell


@app.get("/shells/{aas_identifier}", tags=["AAS Interface"])
async def get_shell(aas_identifier: str):
    sid = _unb64(aas_identifier)
    shell = _SHELLS.get(sid)
    if not shell:
        raise HTTPException(status_code=404, detail="Shell '" + sid + "' not found")
    return shell


@app.put("/shells/{aas_identifier}", tags=["AAS Interface"])
async def update_shell(aas_identifier: str, shell: dict):
    sid = _unb64(aas_identifier)
    if sid not in _SHELLS:
        raise HTTPException(status_code=404, detail="Shell '" + sid + "' not found")
    _SHELLS[sid] = shell
    return shell


@app.delete("/shells/{aas_identifier}", status_code=204, tags=["AAS Interface"])
async def delete_shell(aas_identifier: str):
    sid = _unb64(aas_identifier)
    if sid not in _SHELLS:
        raise HTTPException(status_code=404, detail="Shell '" + sid + "' not found")
    del _SHELLS[sid]


@app.get("/shells/{aas_identifier}/submodels", tags=["AAS Interface"])
async def get_shell_submodel_refs(
    aas_identifier: str,
    limit: int = Query(100, ge=1, le=1000),
    cursor: int = Query(0, ge=0),
):
    sid = _unb64(aas_identifier)
    shell = _SHELLS.get(sid)
    if not shell:
        raise HTTPException(status_code=404, detail="Shell '" + sid + "' not found")
    return _paged(shell.get("submodels", []), limit, cursor)


@app.post("/shells/{aas_identifier}/submodels", tags=["AAS Interface"])
async def add_submodel_ref(aas_identifier: str, ref: dict):
    sid = _unb64(aas_identifier)
    shell = _SHELLS.get(sid)
    if not shell:
        raise HTTPException(status_code=404, detail="Shell '" + sid + "' not found")
    shell.setdefault("submodels", []).append(ref)
    return ref


@app.delete("/shells/{aas_identifier}/submodels/{submodel_identifier}", status_code=204, tags=["AAS Interface"])
async def remove_submodel_ref(aas_identifier: str, submodel_identifier: str):
    sid = _unb64(aas_identifier)
    smid = _unb64(submodel_identifier)
    shell = _SHELLS.get(sid)
    if not shell:
        raise HTTPException(status_code=404, detail="Shell '" + sid + "' not found")
    refs = shell.get("submodels", [])
    shell["submodels"] = [
        r for r in refs
        if not any(k.get("value") == smid for k in r.get("keys", []))
    ]


# ── /submodels ───────────────────────────────────────────────────

@app.get("/submodels", tags=["Submodel Repository"])
async def get_all_submodels(
    limit: int = Query(100, ge=1, le=1000),
    cursor: int = Query(0, ge=0),
):
    return _paged(list(_SUBMODELS.values()), limit, cursor)


@app.post("/submodels", status_code=201, tags=["Submodel Repository"])
async def create_submodel(submodel: dict):
    smid = submodel.get("id") or submodel.get("idShort")
    if not smid:
        raise HTTPException(status_code=400, detail="Submodel must have 'id'")
    if smid in _SUBMODELS:
        raise HTTPException(status_code=409, detail="Submodel '" + str(smid) + "' already exists")
    _SUBMODELS[smid] = submodel
    return submodel


@app.get("/submodels/{submodel_identifier}", tags=["Submodel Interface"])
async def get_submodel(submodel_identifier: str):
    smid = _unb64(submodel_identifier)
    sm = _SUBMODELS.get(smid)
    if not sm:
        raise HTTPException(status_code=404, detail="Submodel '" + smid + "' not found")
    return sm


@app.put("/submodels/{submodel_identifier}", tags=["Submodel Interface"])
async def update_submodel(submodel_identifier: str, submodel: dict):
    smid = _unb64(submodel_identifier)
    if smid not in _SUBMODELS:
        raise HTTPException(status_code=404, detail="Submodel '" + smid + "' not found")
    _SUBMODELS[smid] = submodel
    return submodel


@app.patch("/submodels/{submodel_identifier}", tags=["Submodel Interface"])
async def patch_submodel(submodel_identifier: str, patch: dict):
    smid = _unb64(submodel_identifier)
    if smid not in _SUBMODELS:
        raise HTTPException(status_code=404, detail="Submodel '" + smid + "' not found")
    _SUBMODELS[smid].update(patch)
    return _SUBMODELS[smid]


@app.delete("/submodels/{submodel_identifier}", status_code=204, tags=["Submodel Interface"])
async def delete_submodel(submodel_identifier: str):
    smid = _unb64(submodel_identifier)
    if smid not in _SUBMODELS:
        raise HTTPException(status_code=404, detail="Submodel '" + smid + "' not found")
    del _SUBMODELS[smid]


@app.get("/submodels/{submodel_identifier}/submodel-elements", tags=["Submodel Interface"])
async def get_submodel_elements(
    submodel_identifier: str,
    limit: int = Query(100, ge=1, le=1000),
    cursor: int = Query(0, ge=0),
):
    smid = _unb64(submodel_identifier)
    sm = _SUBMODELS.get(smid)
    if not sm:
        raise HTTPException(status_code=404, detail="Submodel '" + smid + "' not found")
    return _paged(sm.get("submodelElements", []), limit, cursor)


@app.get("/submodels/{submodel_identifier}/submodel-elements/{id_short_path:path}", tags=["Submodel Interface"])
async def get_submodel_element(submodel_identifier: str, id_short_path: str):
    smid = _unb64(submodel_identifier)
    sm = _SUBMODELS.get(smid)
    if not sm:
        raise HTTPException(status_code=404, detail="Submodel '" + smid + "' not found")
    el = _resolve_element(sm.get("submodelElements", []), id_short_path.split("."))
    if el is None:
        raise HTTPException(status_code=404, detail="Element '" + id_short_path + "' not found")
    return el


@app.patch("/submodels/{submodel_identifier}/submodel-elements/{id_short_path:path}", tags=["Submodel Interface"])
async def patch_submodel_element(submodel_identifier: str, id_short_path: str, body: dict):
    smid = _unb64(submodel_identifier)
    sm = _SUBMODELS.get(smid)
    if not sm:
        raise HTTPException(status_code=404, detail="Submodel '" + smid + "' not found")
    el = _resolve_element(sm.get("submodelElements", []), id_short_path.split("."))
    if el is None:
        raise HTTPException(status_code=404, detail="Element '" + id_short_path + "' not found")
    el.update(body)
    return el


@app.put("/submodels/{submodel_identifier}/submodel-elements/{id_short_path:path}", tags=["Submodel Interface"])
async def put_submodel_element(submodel_identifier: str, id_short_path: str, element: dict):
    smid = _unb64(submodel_identifier)
    sm = _SUBMODELS.get(smid)
    if not sm:
        raise HTTPException(status_code=404, detail="Submodel '" + smid + "' not found")
    elements = sm.get("submodelElements", [])
    path = id_short_path.split(".")
    parent = _resolve_element(elements, path[:-1]) if len(path) > 1 else None
    target: list = parent["value"] if parent else elements
    for i, el in enumerate(target):
        if el.get("idShort") == path[-1]:
            target[i] = element
            return element
    target.append(element)
    return element


# ── /concept-descriptions ─────────────────────────────────────────

@app.get("/concept-descriptions", tags=["ConceptDescription Repository"])
async def get_concept_descriptions(
    limit: int = Query(100, ge=1, le=1000),
    cursor: int = Query(0, ge=0),
):
    return _paged(list(_CONCEPT_DESCRIPTIONS.values()), limit, cursor)


@app.post("/concept-descriptions", status_code=201, tags=["ConceptDescription Repository"])
async def create_concept_description(cd: dict):
    cdid = cd.get("id")
    if not cdid:
        raise HTTPException(status_code=400, detail="ConceptDescription must have 'id'")
    _CONCEPT_DESCRIPTIONS[cdid] = cd
    return cd


@app.get("/concept-descriptions/{cd_identifier}", tags=["ConceptDescription Repository"])
async def get_concept_description(cd_identifier: str):
    cdid = _unb64(cd_identifier)
    cd = _CONCEPT_DESCRIPTIONS.get(cdid)
    if not cd:
        raise HTTPException(status_code=404, detail="ConceptDescription '" + cdid + "' not found")
    return cd


@app.put("/concept-descriptions/{cd_identifier}", tags=["ConceptDescription Repository"])
async def put_concept_description(cd_identifier: str, cd: dict):
    cdid = _unb64(cd_identifier)
    _CONCEPT_DESCRIPTIONS[cdid] = cd
    return cd


@app.delete("/concept-descriptions/{cd_identifier}", status_code=204, tags=["ConceptDescription Repository"])
async def delete_concept_description(cd_identifier: str):
    cdid = _unb64(cd_identifier)
    if cdid not in _CONCEPT_DESCRIPTIONS:
        raise HTTPException(status_code=404, detail="ConceptDescription '" + cdid + "' not found")
    del _CONCEPT_DESCRIPTIONS[cdid]


# ── server meta ───────────────────────────────────────────────────

@app.get("/health", tags=["Server"])
async def health():
    return {
        "status": "ok",
        "version": ` + q(version) + `,
        "shells": len(_SHELLS),
        "submodels": len(_SUBMODELS),
        "concept_descriptions": len(_CONCEPT_DESCRIPTIONS),
    }


@app.get("/description", tags=["Server"])
async def description():
    return {
        "profiles": [
            "https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-002",
            "https://admin-shell.io/aas/API/3/0/SubmodelRepositoryServiceSpecification/SSP-002",
            "https://admin-shell.io/aas/API/3/0/ConceptDescriptionRepositoryServiceSpecification/SSP-001",
        ]
    }
`
  );
}

function generateModelsPy(submodels: SubmodelTemplate[]): string {
  const xsdToPy: Record<string, string> = {
    'xs:string': 'str',
    'xs:int': 'int',
    'xs:long': 'int',
    'xs:short': 'int',
    'xs:byte': 'int',
    'xs:double': 'float',
    'xs:float': 'float',
    'xs:boolean': 'bool',
    'xs:date': 'date',
    'xs:dateTime': 'datetime',
    'xs:anyURI': 'str',
    'xs:duration': 'str',
    'xs:decimal': 'Decimal',
  };

  function pyType(el: SubmodelElement | SubmodelElementChild): string {
    switch (el.type) {
      case 'Property': return xsdToPy[el.valueType || 'xs:string'] || 'str';
      case 'MultiLanguageProperty': return 'List[LangString]';
      case 'SubmodelElementCollection': return el.idShort + 'Collection';
      case 'Operation': return 'OperationModel';
      case 'File': return 'FileElement';
      case 'Blob': return 'BlobElement';
      case 'ReferenceElement': return 'Optional[Reference]';
      default: return 'Any';
    }
  }

  function collectionClass(el: SubmodelElement | SubmodelElementChild): string {
    if (el.type !== 'SubmodelElementCollection') return '';
    const smEl = el as SubmodelElement;
    if (!smEl.children || smEl.children.length === 0) return '';
    const fields = smEl.children.map(c => {
      const ft = pyType(c);
      return '    ' + c.idShort + ': Optional[' + ft + '] = None';
    }).join('\n');
    return '\nclass ' + el.idShort + 'Collection(BaseModel):\n' + fields + '\n';
  }

  function submodelClass(sm: SubmodelTemplate): string {
    const nestedClasses = sm.elements
      .filter(e => e.type === 'SubmodelElementCollection')
      .map(e => collectionClass(e))
      .join('');
    const fields = sm.elements.map(e => {
      const ft = pyType(e);
      const wrapped = e.required ? ft : 'Optional[' + ft + ']';
      return '    ' + e.idShort + ': ' + wrapped + ' = None';
    }).join('\n');
    const docstring = '    """' + (sm.description || sm.idShort) + ' — ' + sm.semanticId + '"""';
    return nestedClasses + '\nclass ' + sm.idShort + 'Model(BaseModel):\n' + docstring + '\n' + (fields || '    pass') + '\n';
  }

  const allElements = submodels.flatMap(sm => sm.elements);
  const needsDate = allElements.some(e => e.valueType === 'xs:date' || e.valueType === 'xs:dateTime');
  const needsDecimal = allElements.some(e => e.valueType === 'xs:decimal');

  const dateImport = needsDate ? '\nfrom datetime import date, datetime' : '';
  const decimalImport = needsDecimal ? '\nfrom decimal import Decimal' : '';

  const baseTypes = `

# ── AAS base types ───────────────────────────────────────────────

class LangString(BaseModel):
    language: str = "en"
    text: str = ""


class Key(BaseModel):
    type: str
    value: str


class Reference(BaseModel):
    type: str = "ExternalReference"
    keys: List[Key] = []


class OperationVariable(BaseModel):
    value: Any = None


class OperationModel(BaseModel):
    inputVariables: List[OperationVariable] = []
    outputVariables: List[OperationVariable] = []
    inoutputVariables: List[OperationVariable] = []


class FileElement(BaseModel):
    contentType: str = "application/octet-stream"
    value: Optional[str] = None


class BlobElement(BaseModel):
    contentType: str = "application/octet-stream"
    value: Optional[str] = None

`;

  return (
    'from __future__ import annotations\n\n' +
    'from typing import Any, List, Optional' +
    dateImport +
    decimalImport + '\n\n' +
    'from pydantic import BaseModel\n' +
    baseTypes +
    submodels.map(submodelClass).join('\n')
  );
}

function generateDockerfile(): string {
  return `FROM python:3.12-slim AS builder

WORKDIR /build
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \\
    && pip install --no-cache-dir -r requirements.txt --target /build/deps

FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PYTHONPATH=/app/deps

RUN adduser --disabled-password --gecos "" appuser

WORKDIR /app
COPY --from=builder /build/deps ./deps
COPY . .

USER appuser
EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=10s --retries=3 \\
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"

CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
`;
}

function generateRequirements(): string {
  return `fastapi>=0.110.0
uvicorn[standard]>=0.29.0
pydantic>=2.0.0
python-multipart>=0.0.9
`;
}

function generateDockerCompose(aasIdShort: string, version: string): string {
  const serviceName = aasIdShort.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return (
`services:
  ` + serviceName + `:
    build: .
    container_name: ` + serviceName + `-server
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    labels:
      aas.version: "` + version + `"
      aas.spec: "IDTA-01002-3-0"
`
  );
}

// ═══════════════════════
// MAIN PAGE COMPONENT
// ═══════════════════════

type CodeTab = 'main' | 'models' | 'docker' | 'requirements' | 'compose';

export default function AASServer() {
  const { selectedModelId, setSelectedModelId, availableModels, currentModel, currentVersion } = useAASContext();
  const submodels = currentModel?.submodels ?? [];
  const aasIdShort = currentModel?.idShort ?? '';
  const { setHandlers } = useDialogContext();

  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [genProgress, setGenProgress] = useState<string[]>([]);
  const [activeTab, setActiveTab] = useState<CodeTab>('main');
  const [copied, setCopied] = useState(false);

  const runGeneration = () => {
    setGenerating(true);
    setGenerated(false);
    setGenProgress([]);
    GEN_STEPS.forEach((step, i) => {
      setTimeout(() => {
        setGenProgress(prev => [...prev, step]);
        if (i === GEN_STEPS.length - 1) {
          setGenerating(false);
          setGenerated(true);
        }
      }, (i + 1) * 500);
    });
  };

  const getCode = (): string => {
    if (!generated) return '';
    switch (activeTab) {
      case 'main': return generateMainPy(aasIdShort, currentModel.assetId, currentVersion.version, currentModel.assetKind, submodels);
      case 'models': return generateModelsPy(submodels);
      case 'docker': return generateDockerfile();
      case 'requirements': return generateRequirements();
      case 'compose': return generateDockerCompose(aasIdShort, currentVersion.version);
      default: return '';
    }
  };

  const handleCopy = async () => {
    const code = getCode();
    if (!code) return;
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const code = getCode();
    if (!code) return;
    const fileNames: Record<CodeTab, string> = {
      main: 'main.py',
      models: 'models.py',
      docker: 'Dockerfile',
      requirements: 'requirements.txt',
      compose: 'docker-compose.yml',
    };
    const blob = new Blob([code], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileNames[activeTab];
    a.click();
    URL.revokeObjectURL(url);
  };

  const tabs: { key: CodeTab; label: string }[] = [
    { key: 'main', label: 'main.py' },
    { key: 'models', label: 'models.py' },
    { key: 'docker', label: 'Dockerfile' },
    { key: 'requirements', label: 'requirements.txt' },
    { key: 'compose', label: 'docker-compose.yml' },
  ];

  useEffect(() => {
    setHandlers({ onGenerateServer: runGeneration, onDownloadServer: handleDownload });
    return () => setHandlers({});
  }, [generated, activeTab]);

  // No model available (e.g. the server is unreachable / the session expired so
  // nothing loaded). Render an empty state instead of dereferencing currentModel.
  if (!currentModel) {
    return (
      <Box sx={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', p: 4 }}>
        <Stack spacing={1} alignItems="center">
          <Typography variant="subtitle1" fontWeight={700}>No AAS model available</Typography>
          <Typography variant="body2" color="text.secondary" textAlign="center">
            Create or import a model first. If you expected existing models, your session may have
            expired — try signing in again.
          </Typography>
        </Stack>
      </Box>
    );
  }

  return (
    <Box sx={{ flex: 1, display: 'flex', overflow: 'hidden' }}>

      {/* ── Left Panel ── */}
      <Box
        sx={{
          width: 300,
          borderRight: 1,
          borderColor: 'divider',
          bgcolor: 'background.paper',
          display: 'flex',
          flexDirection: 'column',
          p: 2.25,
          gap: 1.75,
          overflowY: 'auto',
          flexShrink: 0,
        }}
      >
        <Box>
          <Typography variant="subtitle1" fontWeight={700}>Server Generator</Typography>
          <Typography variant="caption" color="text.disabled" fontFamily="monospace" display="block">
            FastAPI · IDTA-01002-3-0
          </Typography>
        </Box>

        <Box>
          <Typography variant="overline" color="text.disabled" display="block" mb={0.75}>AAS Model</Typography>
          <FormControl size="small" fullWidth>
            <Select
              value={selectedModelId}
              onChange={(e) => setSelectedModelId(e.target.value)}
              sx={{ fontFamily: 'monospace', fontSize: 11 }}
            >
              {availableModels.map(m => (
                <MenuItem key={m.id} value={m.id} sx={{ fontFamily: 'monospace', fontSize: 11 }}>
                  {m.idShort.replace('AAS_', '')}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
        </Box>

        <Paper variant="outlined" sx={{ p: 1.75 }}>
          <Typography variant="overline" color="text.disabled" display="block" mb={1.25}>source shell</Typography>
          <Typography variant="body2" fontWeight={600} mb={0.75}>{aasIdShort}</Typography>
          {([
            ['submodels', submodels.length],
            ['properties', submodels.flatMap(s => s.elements).filter(e => e.type === 'Property').length],
            ['operations', submodels.flatMap(s => s.elements).filter(e => e.type === 'Operation').length],
          ] as [string, number][]).map(([k, v]) => (
            <Stack key={k} direction="row" justifyContent="space-between" mb={0.5}>
              <Typography variant="caption" color="text.secondary" fontFamily="monospace">{k}</Typography>
              <Typography variant="caption" color="primary.main" fontFamily="monospace">{v}</Typography>
            </Stack>
          ))}
        </Paper>

        <Button
          variant="contained"
          onClick={runGeneration}
          disabled={generating}
          startIcon={generating || generated ? <RefreshRounded /> : <BoltRounded />}
          sx={{ fontWeight: 600 }}
        >
          {generating ? 'Generating…' : generated ? 'Regenerate' : 'Generate Server'}
        </Button>

        {(generating || generated) && genProgress.length > 0 && (
          <Paper variant="outlined" sx={{ p: 1.75 }}>
            <Stack spacing={0.75}>
              {genProgress.map((step, i) => (
                <Stack key={i} direction="row" alignItems="center" spacing={0.875}>
                  <Box
                    sx={{
                      width: 5, height: 5, borderRadius: '50%', flexShrink: 0,
                      bgcolor: i === genProgress.length - 1 && generated ? 'success.main' : 'text.disabled',
                    }}
                  />
                  <Typography
                    variant="caption"
                    fontFamily="monospace"
                    color={i === genProgress.length - 1 && generated ? 'success.main' : 'text.secondary'}
                  >
                    {step}
                  </Typography>
                </Stack>
              ))}
            </Stack>
          </Paper>
        )}

        {generated && (
          <Paper variant="outlined" sx={{ p: 1.75, borderColor: 'success.main', bgcolor: 'rgba(16,185,129,.05)' }}>
            <Typography variant="caption" fontWeight={600} color="success.main" display="block" mb={0.75}>
              Server config
            </Typography>
            <Typography variant="caption" fontFamily="monospace" color="text.secondary" sx={{ lineHeight: 1.9 }} component="div">
              Host: 0.0.0.0:8000<br />
              Runtime: Python 3.12<br />
              Framework: FastAPI 0.110<br />
              Spec: IDTA-01002-3-0
            </Typography>
          </Paper>
        )}
      </Box>

      {/* ── Right: Code Panel ── */}
      <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
        <Stack
          direction="row"
          alignItems="center"
          sx={{ px: 2, borderBottom: 1, borderColor: 'divider', bgcolor: 'background.paper', flexShrink: 0 }}
        >
          <Tabs
            value={activeTab}
            onChange={(_, v) => setActiveTab(v as CodeTab)}
            textColor="inherit"
            slotProps={{ indicator: { style: { height: 2 } } }}
          >
            {tabs.map(tab => (
              <Tab
                key={tab.key}
                value={tab.key}
                label={tab.label}
                sx={{ fontFamily: 'monospace', fontSize: 11, minHeight: 44, textTransform: 'none' }}
              />
            ))}
          </Tabs>
          <Box flexGrow={1} />
          {generated && (
            <Stack direction="row" spacing={0.75}>
              <Button
                size="small"
                variant="text"
                startIcon={<ContentCopyRounded sx={{ fontSize: 13 }} />}
                onClick={handleCopy}
                color={copied ? 'success' : 'inherit'}
              >
                {copied ? 'Copied!' : 'Copy'}
              </Button>
              <Button
                size="small"
                variant="outlined"
                startIcon={<FileDownloadRounded sx={{ fontSize: 13 }} />}
                onClick={handleDownload}
              >
                Download
              </Button>
            </Stack>
          )}
        </Stack>

        <Box sx={{ flex: 1, overflow: 'auto', p: 2.5 }}>
          {!generated ? (
            <Stack alignItems="center" justifyContent="center" height="100%" spacing={1}>
              <Typography fontSize={30}>⚡</Typography>
              <Typography variant="body2" color="text.secondary" fontWeight={500}>
                Clicca "Generate Server" per iniziare
              </Typography>
              <Typography variant="caption" fontFamily="monospace" color="text.disabled">
                {submodels.length} submodel{submodels.length !== 1 ? 's' : ''} · FastAPI · IDTA compliant
              </Typography>
            </Stack>
          ) : (
            <pre style={{ fontSize: 11, fontFamily: "'JetBrains Mono', 'Fira Code', monospace", lineHeight: 1.7, whiteSpace: 'pre-wrap', margin: 0 }}>
              {getCode()}
            </pre>
          )}
        </Box>
      </Box>
    </Box>
  );
}
